name: slide_countdown
description: A Flutter package to create easy slide animation countdown / countup timer.
version: 0.2.8
homepage: https://github.com/appcapsergen/slide_countdown
maintener: Sergen Peker (@appcapsergen)

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stream_duration: ">=2.0.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
